export let timeLineData = [
    {
      year:'2015',
      desc:'出膜产品在线监控理念',
      img:''
    },
    {
      year:'2016',
      desc:'组织原型开发',
      img:''
    },
    {
      year:'2017',
      desc:'XCOULD膜系统上线',
      img:''
    },
    {
      year:'2018',
      desc:'水务精灵平台上线',
      img:''
    },
    {
      year:'2019',
      desc:'工业市政分布式水处理全流程覆盖',
      img:''
    },
    {
      year:'2020',
      desc:'全线场景接入，专业用户告诉迭代',
      img:''
    },
    {
      year:'2021',
      desc:'启动云图点亮地图',
      img:''
    },
    {
      year:'2022',
      desc:'小精灵saas服务上线',
      img:''
    }
  ]